on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build BBQ20 Firmware
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Cache west modules
      #   uses: actions/cache@v4
      #   env:
      #     cache-name: cache-zephyr-modules
      #   with:
      #     path: |
      #       modules/
      #       tools/
      #       zephyr/
      #       bootloader/
      #       zmk/
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ env.cache-name }}-
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: Check west fetch
        run: |
          echo "--- zmk dir ---"
          ls zmk/
          echo "--- zmk git log ---"
          git -C zmk log --oneline -5
          echo "--- zmk remote ---"
          git -C zmk remote -v
          echo "--- pointing header search ---"
          find zmk -name "pointing.h"
          echo "--- zmk include dir ---"
          ls zmk/app/include/dt-bindings/zmk/

      - name: West Zephyr Export
        run: west zephyr-export

      - name: Debug config path
        run: |
          echo "PWD: $PWD"
          echo "Workspace: ${{ github.workspace }}"
          ls -la config/
          cat config/bbq20.keymap
          echo "Workspace Keymap:"
          cat ${{ github.workspace }}/config/bbq20.keymap || echo "missing workspace keymap" && ls ${{ github.workspace }}/config || echo "workspace config directory missing"
          echo "--- ZMK pointing header ---"
          find . -name "pointing.h" 2>/dev/null
          echo "workspace?"
          find ${{ github.workspace }} -name "pointing.h" 2>/dev/null || echo "unable to run find on workspace"
          echo "--- West list ---"
          west list

      - name: Debug keymaps
        run: |
          find zmk -name "*.keymap" 2>/dev/null
          find zmk -name "bbq20*" 2>/dev/null

      - name: Build BBQ20 Firmware
        run: |
          west build -s zmk/app -b bbq20 -- \
            -DZMK_CONFIG="$PWD/config"

      - name: Get short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Rename firmware
        run: |
          cp build/zephyr/zmk.uf2 "build/zephyr/bbq20_zmk_${SHORT_SHA}.uf2"

      - name: Archive Firmware
        uses: actions/upload-artifact@v4
        with:
          name: bbq20_zmk_${{ env.SHORT_SHA }}
          path: "build/zephyr/bbq20_zmk_${{ env.SHORT_SHA }}.uf2"