on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build BBQ20 Firmware
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Cache west modules
      #   uses: actions/cache@v4
      #   env:
      #     cache-name: cache-zephyr-modules
      #   with:
      #     path: |
      #       modules/
      #       tools/
      #       zephyr/
      #       bootloader/
      #       zmk/
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ env.cache-name }}-
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: West Zephyr Export
        run: west zephyr-export

      - name: Remove pointing.h include
        run: |
          sed -i '/#include <dt-bindings\/zmk\/pointing.h>/d' config/bbq20.keymap

      - name: Build BBQ20 Firmware
        run: |
          west build -s zmk/app -b bbq20 -- \
            -DZMK_CONFIG="$PWD/config"

      - name: Get short SHA
        run: |
          git config --global --add safe.directory /__w/zmk_config_Q20/zmk_config_Q20
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Rename firmware
        run: |
          cp build/zephyr/zmk.uf2 "build/zephyr/bbq20_zmk_${SHORT_SHA}.uf2"

      - name: Archive Firmware
        uses: actions/upload-artifact@v4
        with:
          name: bbq20_zmk_${{ env.SHORT_SHA }}
          path: "build/zephyr/bbq20_zmk_${{ env.SHORT_SHA }}.uf2"